### ISSUE TITLE
In Notebook: AttributeError: 'tqdm' object has no attribute 'sp'

### ISSUE THREAD

**Issue by LIU-Yinyi** [Slimmer-AI/mpire#11]
When using `mpire` in `jupyter notebook`, there is an error when enabling `progress_bar=True`:

```bash
Process ForkProcess-34:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ubuntu/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/mpire/progress_bar.py", line 194, in _progress_bar_handler
    progress_bar.sp(bar_style='success')
AttributeError: 'tqdm' object has no attribute 'sp'
```

After reviewing the codes in Line 194, `sp` seems to be activated only when `in_notebook` is True:

```python
if in_notebook:
    progress_bar.sp(bar_style='success')
```

---

## Testing Environment 
- **OS:** Ubuntu 16.04
- **Interpreter:** Python 3.8.8 [GCC 7.3.0]
- **Libraries:** mpire (2.1.1), tqdm (4.62.2), jupiter (1.0.0)

**Comment by LIU-Yinyi** [comment]
Finally I found where the problem located. In **tqdm 4.62.2**, the API is changed to `disp` instead of `sp` for notebook. Simply modify the codes in Line 169 and 194:

```python
progress_bar.disp(bar_stype='danger')
progress_bar.disp(bar_stype='success')
```

**Comment by sybrenjansen** [comment]
Thnx for locating the problem. I will look for a fix that's backwards compatible and hopefully future proof as well.

**Comment by morganmcg1** [comment]
just hit this too in a (kaggle) notebook, really excited about this library, would be great to have an easy to use progress bar for MP!

**Comment by morganmcg1** [comment]
Its a thing of beauty, thank you!

<img width="938" alt="Screenshot 2021-08-31 at 16 16 25" src="https://user-images.githubusercontent.com/20516801/131529429-1732a83d-1623-4fed-a45d-d31cea2adcb4.png">
