### ISSUE TITLE
`shared_objects` not applicable for Windows?

### ISSUE THREAD

**Issue by ranshadmi** [Slimmer-AI/mpire#18]
Hi,

I've tested the `shared_objects` feature on Windows and saw the copying of the supposedly "shared" objects was still taking place. Then I notice the documentation states that multi-processing with sharing objects is only possible when using `start_method='fork'`, which is not available on Windows...
I've tested the feature on Linux and it worked as expected. Is there a way to make it work on Windows as well?

My sample code to reproduce (have to remove the `start_method='fork'` for it to run on Windows):
```
from time import time
import numpy as np
from mpire import WorkerPool


def main():
    x = 10 + 2 * np.random.randn(10_000_000)  # N(10, 4)
    y = 20 + 1 * np.random.randn(10_000_000)  # N(10, 1)
    n_tests = 100

    print('no multi-processing')
    t0 = time()
    obj_ids = [func((x, y)) for _ in range(n_tests)]
    print(f"{time() - t0:.2f}s, number of copies {len(set(obj_ids))}")

    print('multi-processing')
    t0 = time()
    with WorkerPool(n_jobs=4, start_method='fork') as pool:
        obj_ids = pool.map(func, [((x, y), ) for _ in range(n_tests)])
    print(f"{time() - t0:.2f}s, number of copies {len(set(obj_ids))}")

    print('multi-processing with shared objects')
    t0 = time()
    with WorkerPool(n_jobs=4, shared_objects=(x, y), start_method='fork') as pool:
        obj_ids = pool.map(func, range(n_tests))
    print(f"{time() - t0:.2f}s, number of copies {len(set(obj_ids))}")


def func(d, _=None):
    x, y = d
    diff = np.random.choice(x, size=10_000, replace=False).mean() - np.random.choice(y, size=10_000, replace=False).mean()
    return id(x)


if __name__ == '__main__':
    main()
```

**Comment by sybrenjansen** [comment]
It depends. 

For most python objects this won't work out of the box. As you said, fork is not available on Windows and you need fork for this.

Depending on your use case, though, you could utilize managers that provide a proxy to an object (https://docs.python.org/3/library/multiprocessing.html#managers). This means the object you share lives in its own process and any access has to be communicated over pipes. 

Another option is the use of Python's shared_memory: https://docs.python.org/3/library/multiprocessing.shared_memory.html. But you need Python 3.8 for that and the object you're sharing should be compatible with its interface. Numpy arrays should be compatible.

Hope this helps.

**Comment by sybrenjansen** [comment]
Another option would be to use memory mapping. Save the numpy array to disk and load it with mmap_mode='r'. This should be very memory friendly as it won't load the entire array in memory.

For loading it once per worker you can make use of the worker_init parameter.

**Comment by ranshadmi** [comment]
> For most python objects this won't work out of the box on Windows. As you said, fork is not available on Windows and you need fork for this.

I think it requires some clear "heads-up" in the documentation of shared-object usage of the package. It's an important feature in my view and the fact it doesn't work on Windows is worth mentioning.

**Comment by sybrenjansen** [comment]
Thnx for your feedback. I will try to make it more clear in the docs.

I'm closing this issue for now.

**Comment by xiasummer** [comment]
After almost a year, it's still not working on windows

**Comment by sybrenjansen** [comment]
It's impossible to create something that will work in all circumstances on Windows. The `shared_memory` feature in Python only works on some objects (mostly numpy arrays, but lists with some restrictions work as well) and using managers can be cumbersome when a lot of communication is required from/to that object. So, creating something that will work automatically is not desired.

What I could do, however, is add some utility functions that will wrap objects semi-automatically using `shared_memory` or `multiprocessing.Manager`. In that case you import a wrap function, pass the object that you want to share across processes to that wrap function and receive a wrapped object back, and finally pass that wrapped object as `shared_objects` to mpire.

It could look, for example, as follows:

```
from mpire.utils import numpy_to_shared_memory

arr = np.array(...)
wrapped_arr = numpy_to_shared_memory(arr)

with WorkerPool(4, shared_objects=wrapped_arr) as pool:
    pool.map(...)
```
In this example `wrapped_arr` can be written to and read from simultaneously and any change will be reflected in `arr`. This will work for shared memory objects.

How does that solution sound?

**Comment by ranshadmi** [comment]
My intended use case was originally sharing a lot of read-only data between the processes (they were all assigned a part of the data and had to process it). No writing to a shared location was necessary. But hi, that was just my use-case. Does such a use case change your opinion about using managers?

As for your suggestion, I would love to have the ability to use custom objects (not just numpy arrays) but I guess that's something I can work with.

Another note is that I think the API should be identical across platforms (windows/linux) since the code, at least in my case, is sometimes written on a windows and runs on a either windows/linux machines. So if you could implement your suggestion "transparently" and maybe raise an exception (or warning?) if trying to share a not-really-shareable-on-windows object, that would be great...
