### ISSUE TITLE
missing 1 required positional argument when inputting list of pandas dataframe

### ISSUE THREAD

**Issue by vinson2233** [Slimmer-AI/mpire#29]
Python version : 3.7.10
mpire version : 2.3.3

I'm working on multiple time series problem where I split the dataframe according to the product_id and do individual forecasting to each product_id. I usually use multiprocessing, and after I found about `mpire`, i decide to try to give a go, but failed. Here's a smallest reproducible piece of code to simulate my situation :

This is the code using python's multiprocessing
```
from multiprocessing import Pool
import pandas as pd

def time_consuming_function(x):
    return 0

empty_df = pd.DataFrame()
list_df = [empty_df,empty_df]

with Pool(processes=5) as pool:
    results = pool.map(time_consuming_function, list_df)
print(results)
```
the result is `[0,0]` which is expected

When I change it to mpire : 
```
from multiprocessing import Pool
import pandas as pd

def time_consuming_function(x):
    return 0

empty_df = pd.DataFrame()
list_df = [empty_df,empty_df]

from mpire import WorkerPool

with WorkerPool(n_jobs=5) as pool:
    results = pool.map(time_consuming_function, list_df)
print(results)
```

It raise this error
```
Traceback (most recent call last):
  File "untitled.py", line 18, in <module>
    results = pool.map(time_consuming_function, list_df)
  File "/opt/conda/lib/python3.7/site-packages/mpire/pool.py", line 267, in map
    progress_bar, progress_bar_position, enable_insights, worker_init, worker_exit)
  File "/opt/conda/lib/python3.7/site-packages/mpire/pool.py", line 326, in map_unordered
    enable_insights, worker_init, worker_exit))
  File "/opt/conda/lib/python3.7/site-packages/mpire/pool.py", line 550, in imap_unordered
    self._handle_exception(progress_bar_handler)
  File "/opt/conda/lib/python3.7/site-packages/mpire/pool.py", line 615, in _handle_exception
    raise err(traceback_str)
TypeError: 

Exception occurred in Worker-0 with the following arguments:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/mpire/worker.py", line 322, in _run_safely
    results = func()
  File "/opt/conda/lib/python3.7/site-packages/mpire/worker.py", line 276, in _func
    results = func(args)
  File "/opt/conda/lib/python3.7/site-packages/mpire/worker.py", line 415, in _helper_func_with_idx
    return args[0], self._call_func(func, args[1])
  File "/opt/conda/lib/python3.7/site-packages/mpire/worker.py", line 440, in _call_func
    return func(*args)
TypeError: time_consuming_function() missing 1 required positional argument: 'x'
```

**Comment by sybrenjansen** [comment]
Hi @vinson2233 , there's a small difference between mpire and vanilla multiprocessing and that is that mpire by default does argument unpacking (similar to `starmap` in some other libraries). In other words, the value is passed like `func(*value)` or `func(**value)` when you're passing a dictionary.

This means that if you pass `[(1, 2, 3), (4, 5, 6), ...]` as iterable then you will need a function with a signature like `def foo(a, b, c)`. In your case, passing an empty dataframe will result in zero values being passed on, as `func(*empty_dataframe)` equals `func()`. 

To circumvent this you can wrap your values in a single value tuple, like so:
```
list_df = [(empty_df,), (empty_df,)]
```
and then it should work as expected. Alternatively, you can use a utility function:
```
from mpire.utils import make_single_arguments

list_df = [empty_df,empty_df]
list_df = make_single_arguments(list_df, generator=False)
```
For more information, please refer to the docs: https://slimmer-ai.github.io/mpire/usage/map/map.html#circumvent-argument-unpacking.

**Comment by vinson2233** [comment]
Nice, thanks for the response, it work quite well for now with `make_single_arguments `.
