### ISSUE TITLE
Always install dataclasses

### ISSUE THREAD

**Issue by sailxjx** [Slimmer-AI/mpire#30]
When I install mpire from `pip install mpire`, it will always install dataclasses, even if there is a [judgment](https://github.com/Slimmer-AI/mpire/blob/master/setup.py#L6)

This is very confusing and makes this dependency unusable in our library. Please fix this problem as soon as possible.

python version: 3.8.6
mpire version: 2.3.3

**Comment by sybrenjansen** [comment]
@sailxjx  that is odd. It seems that installing from source using `pip install .` behaves differently from `pip install mpire`. I will investigate this further and will keep you posted.

**Comment by sybrenjansen** [comment]
I will apply PEP 508, which will hopefully resolve it. This fix will be added to the next release of MPIRE.

**Comment by sailxjx** [comment]
Glad to hear it.

**Comment by sybrenjansen** [comment]
Fixed in v2.3.4
