### ISSUE TITLE
python does not work properly in jupyter notebook after long time running mpire

### ISSUE THREAD

**Issue by ichobits** [Slimmer-AI/mpire#35]
os: ubuntu 20.04 LTS
conda : python 3.8
jupyter notebook

question:
I filter the data from two tsv file use mpire.
Get the data after running for a long time.
however, the python can not work when i run the next cell .

1.run first the mpire ,ok
2. mpire return the data, but  not show in the Variable inspector
3. run the next cell ,the python will not work properly . but ,python use the one cpu core  100% ,  like Into the infinite loop，can not return results.
4. then , interrupt the cell . 
5. run the cell again ,the data will return .

so, I had to run the program manually.  

Can you find the cause of this problem？

two  files uesd in my program : 
interval_input  has rows  2070751
hg19_hg38_relation_input  has rows  3299923

run time ~ 14 hours
cpu :  8 cores ,all used
total RAM: 32GB,  python used in running ~12GB,  system used ~ 3.5GB

code:

```
def get_hg_relation(chr_name, pos_hg19_start, pos_hg19_end, pos_relation):
    pos_relation_filter_tmp =  (pos_relation['chr'].isin([chr_name])) & (pos_relation['pos_hg19'].isin(range(pos_hg19_start,pos_hg19_end+1)))
    pos_relation_filter=pos_relation[pos_relation_filter_tmp==True]
    return pos_relation_filter


# use mipre 
args_isin=[(x, y, z, hg19_hg38_relation_input) for x,y,z in zip(interval_input['chr'], interval_input['pos_hg19_str'],interval_input['pos_hg19_end'])]

with WorkerPool(n_jobs=7) as pool:
    hg_relation_result = pool.map(get_hg_relation, args_isin, enable_insights=True, progress_bar=True)
#     print(hg_relation_result)
    print(pool.get_insights())

```

**Comment by sybrenjansen** [comment]
Sorry to hear you're running into some issues. However, it's a very specific use case you're describing and it's hard to reproduce at my end.  I've run many jobs in a notebook which took hours and everything was working for me.

Could you create a minimal working example where it fails for you? Ideally with data that is generated so I can really test it

**Comment by ichobits** [comment]
> Sorry to hear you're running into some issues. However, it's a very specific use case you're describing and it's hard to reproduce at my end. I've run many jobs in a notebook which took hours and everything was working for me.
> 
> Could you create a minimal working example where it fails for you? Ideally with data that is generated so I can really test it

ok, i will test min dataset for this issues

**Comment by ichobits** [comment]
> Sorry to hear you're running into some issues. However, it's a very specific use case you're describing and it's hard to reproduce at my end. I've run many jobs in a notebook which took hours and everything was working for me.
> 
> Could you create a minimal working example where it fails for you? Ideally with data that is generated so I can really test it

https://anonfiles.com/T8d4N9S3x8/test_mpire_zip
 I upload data to cloud.

If  mpire  runs  onece , maybe will must manual interrupt .
In the htop , the process :  python -m ipython_launcher   soft_path  xxxxx
has cpu 100% .  after interrupt  cell ,it will die.
Then run cell again,  notebook cell will get result.

**Comment by ichobits** [comment]
> Sorry to hear you're running into some issues. However, it's a very specific use case you're describing and it's hard to reproduce at my end. I've run many jobs in a notebook which took hours and everything was working for me.
> 
> Could you create a minimal working example where it fails for you? Ideally with data that is generated so I can really test it

test mpire in windows jupyter notebook
has a error

```
Exception occurred in Worker-5 with the following arguments:
Arg 0: 'chr1'
Arg 1: 1616982
Arg 2: 1617182
Arg 3:          chr   pos_hg19   pos_hg38
0       chr1      10250      10250
1       chr1      10543      10543
2       chr1      13868      13868
3       chr1      14653      14653
4       chr1      14907      14907
...      ...        ...        ...
499995  chr4  148307604  150097237
499996  chr4  148310312  150098085
499997  chr4  148310348  150107047
499998  chr4  148310358  150108512
499999  chr4  148313362  150117514

[500000 rows x 3 columns]
Traceback (most recent call last):
  File "C:\Users\asus\anaconda3\lib\site-packages\mpire\worker.py", line 322, in _run_safely
    results = func()
  File "C:\Users\asus\anaconda3\lib\site-packages\mpire\worker.py", line 276, in _func
    results = func(args)
  File "C:\Users\asus\anaconda3\lib\site-packages\mpire\worker.py", line 415, in _helper_func_with_idx
    return args[0], self._call_func(func, args[1])
  File "C:\Users\asus\anaconda3\lib\site-packages\mpire\worker.py", line 440, in _call_func
    return func(*args)
  File "<ipython-input-10-de0bf6abbee2>", line 5, in get_hg_relation
NameError: name 'pd' is not defined
```
