### ISSUE TITLE
Doc should highlight performance features

### ISSUE THREAD

**Issue by zpz** [Slimmer-AI/mpire#38]
From my perspective, I'm mainly interested in a performant alternative to the standard multiprocessing. While the benchmark is attractive, the readme does not say what tricks in the package make it faster, and make what kind of things faster. The progress bar, insights, init and such are nice to haves but not related to performance. The benchmarks without some explanation for the reason are not enough to make me try this package (for performance reasons).

**Comment by sybrenjansen** [comment]
Good point. I do refer to the blog post, but I'll add some more explanatory text about why it's faster and in what circumstances to the readme in the next update
