### ISSUE TITLE
Example cases won't run

### ISSUE THREAD

**Issue by JWingUtk** [Slimmer-AI/mpire#41]
Similar to #40
I have been attempting to use this package for my highly parallel tasks as well, but even the examples won't run properly on my system. I am on Windows 10 and running on a 3.8+ distribution of Anaconda. Installed mpire via pip.

![image](https://user-images.githubusercontent.com/97312558/164914079-41935b30-008e-40c2-aae4-443c62f4e739.png)

When run, the script fails and gives an enormous traceback and will not respond to user requests to stop execution. A kernel restart is usually required to address this.

![image](https://user-images.githubusercontent.com/97312558/164914123-acc97668-21e2-4576-aa16-f609e9309cbd.png)

**Comment by sybrenjansen** [comment]
Hi @JWingUtk, have a look at https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support, which explains this error message. 

The traceback actually reports the solution you need to implement. Try adding the `freeze_support()` line directly after `if __name__ == '__main__':
