### ISSUE TITLE
Opt-out of dill

### ISSUE THREAD

**Issue by ddelange** [Slimmer-AI/mpire#49]
Hi! :wave:

A user might want to set an env var or similar to opt-out of dill. e.g. https://github.com/dano/aioprocessing#whats-new

**Comment by sybrenjansen** [comment]
Hi. Why not just set `use_dill=False` when constructing a pool? 

Or can you share a use case where an env var should override this flag?

**Comment by ddelange** [comment]
Ah nice, I didn't catch this setting and its default! In that case no need, will close
