### ISSUE TITLE
Terminal freeze due to progress bar?

### ISSUE THREAD

**Issue by Erickwilts** [Slimmer-AI/mpire#53]
My terminal seems to freeze after a script terminates, but only if I'm using a progress bar. Typing `reset` 'unfreezes' the terminal, but also clears the screen. Could it be that the progress bar isn't closed correctly?

I'm using Python 3.8.12 on Ubuntu 20.04.4 LTS in a `tmux` terminal.

**Comment by sybrenjansen** [comment]
I've been trying to reproduce your issue in a tmux terminal with python 3.8.12 (although I'm using fedora 36), but my terminal seems just fine. 

Can you share a minimal working example where it freezes for you? Maybe it has to do with some specific mpire functionality.

**Comment by Erickwilts** [comment]
@sybrenjansen Thanks for your reply. I might have been too quick blaming mpire/tqdm, because I can't create a minimal example that reproduces this. I'll look further into what else could be the issue here.

**Comment by sybrenjansen** [comment]
Alright. Then I'll close this issue for now. If it pops up again and you can create a minimal example then feel free to reopen this one (or create a new one)

**Comment by Erickwilts** [comment]
I figured it out. It had to do with `ffmpeg` and `subprocess` causing stdin to hide keystrokes from the terminal. See [this](https://stackoverflow.com/questions/6488275) if you're interested. Not sure why I didn't notice this happening before I used `mpire` though.
