### ISSUE TITLE
Unexpected expansion of parameter when working with lists of lists

### ISSUE THREAD

**Issue by apacha** [Slimmer-AI/mpire#54]
We would like to use mpire to parallelize processing. We have lists of lists (batches, with n elements each) and use something like this

```python
from mpire import WorkerPool

def print_for_me(file_list: List[str]):
    for file in file_list:
        print(f"Files: {file}")

batches = [["as", "bd"], ["bc", "dc"]]
# This does not work
with WorkerPool(n_jobs=2) as pool:
    pool.map(print_for_me, batches)

# This works, but it super weird to read
with WorkerPool(n_jobs=2) as pool:
    pool.map(print_for_me, zip(batches,))
```

While writing this issue, I had another idea and maybe this is the proper way how to map lists of lists with mpire:

```python
from mpire import WorkerPool

def print_for_me2(*file_list):
    for file in file_list:
        print(f"Files: {file}")

batches = [["as", "bd"], ["bc", "dc"]]
with WorkerPool(n_jobs=2) as pool:
    pool.map(print_for_me2, batches)
```

This maps the list to tuples inside `print_for_me2`, but at least works as expected. Would it be possible with mpire to preserve the inner list, or is this by design impossible?

If this is the recommended way, would it be possible to add 1-2 examples like these to the documentation? That would be great.

**Comment by sybrenjansen** [comment]
Changing it is possible, but that would potentially break a lot of existing software that rely on this behavior. 

There is documentation on this already available: https://slimmer-ai.github.io/mpire/usage/map/map.html#circumvent-argument-unpacking, which also shows how to avoid unpacking (well, it's more of a workaround). 

Please let me know if this fixes your current issues.

**Comment by apacha** [comment]
Yes, that definitely helps. I didn't see that part of the documentation. Thanks a lot!
