### ISSUE TITLE
Progress bar description

### ISSUE THREAD

**Issue by apacha** [Slimmer-AI/mpire#57]
MPIRE uses TQDM as a progress-bar, which is very nice. However, it would be great if there was the possibility to somehow control the progress-bar with the parameters that are available, e.g., the `desc`ription. We have several progress bars in our app and it would be nice to see not only that something is happening, but also _what_ is happening.

Do you think that would be a possible expansion of MPIRE? Is there another way how you can configure TQDM? If yes, where can I find this information in the documentation?

**Comment by sybrenjansen** [comment]
I can add a ``progress_bar_options`` parameter to the map functions that is then passed on to the tqdm progress bar upon creation. As the progress bar lives in another thread and is not accessible, live updates to the description would require quite the overhaul. 

Would this approach be acceptable for your usecase?

**Comment by apacha** [comment]
Having a single `progress_bar_options` parameter would be absolutely sufficient, as most options like the `desc`ription or the `smoothing` only needs to be set once while creating the progress bar anyway.

**Comment by sybrenjansen** [comment]
Added to v2.6.0
