### ISSUE TITLE
Can non blocking asynchronous map be supported?

### ISSUE THREAD

**Issue by kev123456** [Slimmer-AI/mpire#59]
Can non blocking asynchronous map be supported?

**Comment by sybrenjansen** [comment]
Please be a bit more descriptive when asking a question. But I'll try to answer it anyway.

MPIRE supports `imap` and `imap_unordered`, which are both non blocking asynchronous map functions. 

If, on the other hand, you're referring to something similar to asyncio (using coroutines/futures), then no, there are no plans at the moment to support that.

Or did you mean something else?

**Comment by sybrenjansen** [comment]
Did not receive a reply in two months. Closing this for now
