### ISSUE TITLE
ValueError: signal only works in main thread of the main interpreter

### ISSUE THREAD

**Issue by charleslstone** [Slimmer-AI/mpire#61]
Greetings. I am trying to use mpire to improve a long-running function's performance as compared to multiprocess.Pool (which works fine) and am getting this error. Thank you in advance for your help.

I did see the closed issue related to the same error msg.  Full trace below.

I pip installed mpire on Windows 10, Python 3.10.2, Django 4.0.2.    I am not running any threading but am sure what Django does under the covers.  I know others have mpire working with Django.

Code (skinnied down, the run_monte_carlo_mp() func is called from a different module.)
def run_monte_carlo_mp(pd, s):
    from time import time_ns, sleep
    import multiprocessing
    from mpire import WorkerPool
    from rpm.main_calc import calc_years

    iterations = 500
    cpus = 4
    time_start = time_ns()

    # This runs fine in about 7-8 seconds vs 25 secs without multiprocessing.
    with multiprocessing.Pool(processes=cpus) as pool:
        inputs = [[pd, 1] for i in range(iterations)]
        pool.starmap(calc_years, inputs)
    print('multiprocessing.Pool time:', time_ns() - time_start)

    time_start = time_ns()
    # This generates the error below.
    with WorkerPool(n_jobs=cpus) as pool:
        # pd is a python dictionary containing info needed by calc_years_mp()
        inputs = [[pd, 1] for i in range(iterations)]
        pool.map(calc_years, inputs)
    print('mpire.WorkerPool time:', time_ns() - time_start)

--> Traceback (most recent call last):
-->   File "main.py", line 78, in load_plan
-->     run_monte_carlo_mp(pd, 1)
-->   File "multiprocess_test.py", line 27, in run_monte_carlo_mp
-->     pool.map(calc_years, inputs)
-->   File "D:\RPM\env\lib\site-packages\mpire\pool.py", line 265, in map
-->     results = self.map_unordered(func, ((args_idx, args) for args_idx, args in enumerate(iterable_of_args)),
-->   File "D:\RPM\env\lib\site-packages\mpire\pool.py", line 324, in map_unordered
-->     return list(self.imap_unordered(func, iterable_of_args, iterable_len, max_tasks_active, chunk_size,
-->   File "D:\RPM\env\lib\site-packages\mpire\pool.py", line 509, in imap_unordered
-->     self._start_workers(progress_bar)
-->   File "D:\RPM\env\lib\site-packages\mpire\pool.py", line 148, in _start_workers
-->     self._workers.append(self._start_worker(worker_id))
-->   File "D:\RPM\env\lib\site-packages\mpire\pool.py", line 175, in _start_worker
-->     with DisableKeyboardInterruptSignal():
-->   File "D:\RPM\env\lib\site-packages\mpire\signal.py", line 37, in __enter__
-->     ignore_keyboard_interrupt()
-->   File "D:\RPM\env\lib\site-packages\mpire\signal.py", line 45, in ignore_keyboard_interrupt
-->     signal_(SIGINT, SIG_IGN)
-->   File "C:\Users\Dad\AppData\Local\Programs\Python\Python310\lib\signal.py", line 56, in signal
-->     handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
--> ValueError: signal only works in main thread of the main interpreter

**Comment by sybrenjansen** [comment]
Given you're traceback I think you're still on an older version of mpire, probably v2.3.5 or before. This issue was reported in https://github.com/Slimmer-AI/mpire/issues/44 and is fixed in v2.4.0. 

Please try it with a newer version and let me know if that fixes your issue.

**Comment by charleslstone** [comment]
Thank you for your quick reply.  I had mistakenly assumed pip install mpire would give the latest, but was mistaken.  I have 2.3.3.   Tried to upgrade and install mpire==2.5.0 and neither worked (see error below).   So I ran pip uninstall mpire which successfully uninstalled.

pip install mpire==2.5.0 gives me this error: 

Collecting mpire==2.5.0
  Using cached mpire-2.5.0-py3-none-any.whl (288 kB)
Requirement already satisfied: tqdm>=4.27 in d:\rpm\env\lib\site-packages (from mpire==2.5.0) (4.64.0)
ERROR: Could not find a version that satisfies the requirement pywin32==225; platform_system == "Windows" (from mpire) (from versions: 302, 303, 304)
ERROR: No matching distribution found for pywin32==225; platform_system == "Windows"

Ditto for pip install mpire==2.4.0

FYI, I have pywin32 v304 installed.  I am running python v3.10.2 (which is not shown as a supported version on PyPI, but your docs say Python >= 3.6.

I also tried downversioning pywin32 to 225, but that gave me:
pip install pywin32==225
ERROR: Could not find a version that satisfies the requirement pywin32==225 (from versions: 302, 303, 304)
ERROR: No matching distribution found for pywin32==225

Any suggestions?
Thanks very much.
Charlie Stone

**Comment by sybrenjansen** [comment]
Ah yes, python 3.10 support is almost there. In fact, there's a PR for that right now. And I expect that a new release will be there either next week or the week after.

If you can't wait, you can do one of two things:
- clone the repo and install from the exceptions branch
- clone the repo and change pywin32==225 to pywin32>=301 I believe (I'm typing this from memory), in the setup.py file

**Comment by charleslstone** [comment]
Thanks very much again for getting back to me earlier today.  I will do some more head scratching and may give your suggestion a whirl...or may just wait since I have lots of other, related things to work on this project.
All the best,
Charlie

**Comment by charleslstone** [comment]
I was attempting to use an unsupported version of Python.  sybrenjansen gave me 3 options to resolve my issue...many thanks for the great support!
