### ISSUE TITLE
Is there a way to print the progress to a file? 

### ISSUE THREAD

**Issue by xiasummer** [Slimmer-AI/mpire#64]
Because I need to update the progress to a webpage, and cannot embed the console to the webpage.

**Comment by sybrenjansen** [comment]
mpire uses tqdm under the hood, which writes to stderr by default. So you could redirect stderr to a file, no problem. 

Have a look here:
- https://github.com/tqdm/tqdm#redirecting-writing
- https://stackoverflow.com/questions/69576076/is-there-a-way-to-save-tqdm-console-output-to-a-file

You can pass on the `file` argument of tqdm to `progress_bar_options` as detailed here: https://slimmer-ai.github.io/mpire/usage/map/progress_bar.html#progress-bar-options.

Let me know if this helps.

**Comment by xiasummer** [comment]
Great! Thank you!
