### ISSUE TITLE
Error handling for connection refused when attempting to use dashboard

### ISSUE THREAD

**Issue by HeeebsInc** [Slimmer-AI/mpire#68]
I want to start by saying this repository is sweet!  Really love what you did here and we have been using this extensively for a lot of our operations

I have been dealing with a race condition that occurs when a dashboard is running in another container, and a process in a different container attempts to connect to it.  I see the ConnectionRefused error which destroys the pipeline.  

I've attempted to handle the error outside the scope of the package with no luck.  Would it be possible to add a flag or handle the error in the package itself?  

So if a connection attempt is made and fails, the multiprocessing pipeline continues without updating the pbar in the browser.  We could also throw a warning

Let me know if I can help with this!

**Comment by sybrenjansen** [comment]
Thnx for the kind words! :)

In your situation, the dashboard in one container hasn't started yet, but the other process already wants to connect. Is that a correct summary of your race condition? 

The change you suggest sounds good to me. And let's definitely throw a warning if that happens.

Is your error triggered in `mpire.dashboard.manager.get_manager_client_dicts`? This is called from `mpire.progress_bar.ProgressBar._register_progress_bar`. We can catch the error there, throw a warning, and return. That should be enough I believe. Perhaps you can try it out locally and check whether it works. If so, feel free to create a PR for it.

**Comment by HeeebsInc** [comment]
Correct.  There have been cases where the dashboard did start up in time but the connection between containers failed.  I want to chalk it up to docker networking but I'm still troubleshooting.  As I mentioned, the quick fix will be to throw a warning that the dashboard did not connect properly.  We can even add a flag to force a connection if you think that would be helpful too

**Comment by sybrenjansen** [comment]
Adding a flag would be a useful addition, indeed. 

I'm currently busy with some architectural changes in mpire. This will take a while to finish, so I can't work on this one in the near feature (few weeks). If you don't mind waiting, I'll integrate it with that release when I'm done. Otherwise, feel free to make a PR yourself in the mean time.

**Comment by sybrenjansen** [comment]
I want to go about it a bit differently.

If you want to use a dashboard you will have to call `connect_to_dashboard` first. This function actually only sets some parameters and the actual connecting to the dashboard happens later.

I want to change this such that this function will also check if it can establish a connection. If not, it will raise `ConnectionRefused`. In your code you can put a try/except around this function call, and then it shouldn't fail later on.

Is this a good solution for you as well?

**Comment by sybrenjansen** [comment]
Released in v2.7.0
