### ISSUE TITLE
Unclear documentation on how to use dill.

### ISSUE THREAD

**Issue by dominik-strutz** [Slimmer-AI/mpire#69]
Hi everyone,

It is unclear how to use dill if the extras_require install option is not used (or the package is installed using conda). Even if dill is installed, the error message will say that dill is missing despite the problem being that multiprocess is not installed due to the way the following check is implemented:

`try:
    import multiprocess
    DILL_INSTALLED = True
except ImportError:
    DILL_INSTALLED = False`

The resulting error message

`("Can't use dill as the dependencies are not installed. Use `pip install mpire[dill]` to install the required dependencies.")`

gives no hint that it is necessary to install multiprocess to use dill. I only found a mention of this on the welcome page of the documentation.

Adding a sentence to the error message should make it easier for people to solve this problem without looking into the source code. If you are busy, I could also look at how to solve this issue best and write up a pull request.

Thanks for this fantastic package!

**Comment by sybrenjansen** [comment]
Hi @dominik-strutz. That's a very good point. I'm already busy with adding some changes to the repo, so might as well add this to the list. 

Thnx for pointing it out!

**Comment by sybrenjansen** [comment]
Released in v2.7.0
